#!/bin/env zsh
#This file used to define emacs env, emacs will not load zshrc...
# Environment variables should be set in .profile or .zshenv rather than
# .bashrc or .zshrc.

# User configuration
# go work path
uname -a | grep 'Darwin' > /dev/null
if [ $? = 0 ]; then
    export GOROOT="/usr/local/opt/go/libexec"
else
    export GOROOT="/usr/lib/go"
fi
export GOPATH="$HOME/Workspace/go"
export GOBIN="$GOPATH/bin"
export GOPATH="$GOPATH/lib:$GOPATH"

# python work path
# python3 pack pythonPath
export PYTHONPATH="$HOME/Workspace/py/pkg"
export PYBIN="$HOME/Workspace/py/bin"

# set convenient path
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
# path for go
export PATH="$PATH:$GOROOT/bin:$GOBIN"
# path for py
export PATH="$PATH:$PYBIN"
# path for emacs
export PATH="$PATH:/usr/local/Cellar/emacs-plus/25.1/bin"


export CWORKPATH="$HOME/Workspace/c"
# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"
## for magit
#export GIT_EDITOR="/Applications/Emacs.app/Contents/MacOS/Emacs"

# Path Extra
# path for opencv3
# export PATH="$PATH:/usr/local/opt/opencv3/bin"
# export PYTHONPATH="$PYTHONPATH:/usr/local/opt/opencv3/lib/python3.6/site-packages"

# java
# export JAVA_HOME="/Library/Java/Home"
export CLASSPATH=".:./target/classes"

export MAGIC_DIVIDER="$HOME/.oh-my-zsh/divider.png"
