# Path to your oh-my-zsh installation.
# font color (255,223,95)
# background color (18,18,18)
# red        (251,73,52)
# green      (121,187,38)
# yellow     (250,189,47)
# blue       (81,153,240) #5199f0
# cyan       (131,165,152)
# purple     (211,134,155)
# aqua       (142,192,124)
# orange     (254,128,25)
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mephis-magic"


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
# colored-man-pages : make man doc colorful
# vi-mode:      start vi mode in zsh, but default is insert mode;
# Z :           jump to you frequent dir : z zsh plugins z
plugins=(git colored-man-pages vi-mode Z zsh-syntax-highlighting)

# User configuration
# go work path
export GOROOT="/usr/local/go"
export GOPATH="$HOME/Desktop/work/go"
export GOBIN="$GOPATH/bin"
export GOPATH="$GOPATH/lib:$GOPATH"

# python work path
# python3 pack pythonPath
export PYTHONPATH="$HOME/Desktop/work/py/pkg"
export PYBIN="$HOME/Desktop/work/py/bin"

# set convenient path
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
# path for go
export PATH="$PATH:$GOROOT/bin:$GOBIN"
# path for py
export PATH="$PATH:$PYBIN"

export CWORKPATH="$HOME/Desktop/work/c"


source $ZSH/oh-my-zsh.sh
#set up tab completion for arcanist

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"

# run while zsh init
# node manager
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
# export MANPATH="/usr/local/man:$MANPATH"
# use node4.0.0 default
eval "nvm use 5.7.1"
# add more color for item
#source ~/.oh-my-zsh/gruvbox_256palette_osx.sh
source ~/.oh-my-zsh/gruvbox_256palette.sh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
#
# Example aliases
alias p3='python3'
alias netpart='sudo netstat -an | grep'
alias vimrc='vim ~/.vim/vimrc'
alias zshrc='vim ~/.zshrc'
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
#. ~/.vim/bundle/powerline/powerline/bindings/zsh/powerline.zsh
#
#this just for django mysql 
